# Generated by Django 5.0.7 on 2024-08-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titular', models.CharField(max_length=20)),
                ('numero_conta', models.CharField(max_length=5, unique=True)),
                ('moeda', models.CharField(choices=[('real', 'Real'), ('dolar', 'Dólar'), ('euro', 'Euro')], max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
